### ISSUE TITLE
Permission error - ACL not working correctly?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.simple-api#24]
Steps:

- Create a new user called "simpleapi"
- Create a new group called "api"
- Assign the new user to that group
- Configure simpleapi instance to use the new user as default (without authentication)

![Screenshot 2019-10-19 at 18 04 02](https://user-images.githubusercontent.com/1959049/67148018-db524c80-f29a-11e9-922b-f71b9dff4a17.png)

Configure new group as owner of data point

![Screenshot 2019-10-19 at 18 05 10](https://user-images.githubusercontent.com/1959049/67148036-05a40a00-f29b-11e9-8bc2-439c69b776d8.png)

Use set or toggle for endpoint.

- ```/set/hm-rpc.0.OEQ0181555.1.STATE?value=true```
- ```/toggle/hm-rpc.0.OEQ0181555.1.STATE```

Both lead to "permission error" ```No permission for "system.user.simpleapi" to call toggle```

**Comment by Apollon77** [comment]
Which js-controller?
Please also show rights from the group and the user assignment

**Comment by klein0r** [comment]
Found the issue... seems like I've clicked "cancel" after setting the group permissions. 😢

**Comment by Apollon77** [comment]
;-))

**Comment by f11h** [comment]
It seems like I have to reopen this issue and this time it's not the wrong save button ;-)

I have a similar setup like @klein0r but with activated authentification.

![image](https://user-images.githubusercontent.com/31076102/82741869-311e3400-9d57-11ea-8394-0e626238c6f8.png)

I have a user api_user in the group api. The permissions for the group are empty because I want that the users of the group api can only access one datepoint.

![image](https://user-images.githubusercontent.com/31076102/82741881-54e17a00-9d57-11ea-8f93-cbb3d9109def.png)

The permission setup of my datapoint looks like this:

![image](https://user-images.githubusercontent.com/31076102/82741888-6fb3ee80-9d57-11ea-8e5a-ae0f24a47068.png)

When I call the following URI
```https://iobroker.address:9999/get/my.datapoint.id?user=api_user&pass=s3cur3```
I just get

```
{
    "error": "permissionError"
}
```

When I add the read permissions for the api usergroup everything works fine, but the user then can read all datapoints. At the moment one workaround would be activating the option "Nur erlauben wenn Anwender auch Besitzer ist" and assign the datapoint to my API User.

Any idea what could be wrong?
I'm using adapter version 2.4.5 with js-controller version 2.2.9

**Comment by Apollon77** [comment]
Commenting a closed 7 month old ticket makes no sense. Please open a new issue.

**Comment by krichter722** [comment]
@f11h Did you open a new issue by chance?

**Comment by f11h** [comment]
No I didn't open up a new issue for this. (But I also didn't find a solution for this problem - I just don't use it anymore)
